agent:
  mode: release
  port: 8089
  readTimeout: 60s
  writeTimeout: 60s

api:

registry:
  type: consul
  consul:
    address: ''
    token: ''

store:
  type: 'mysql'
  mysql:

  mongo:


logger:
  savePath: 'log'
  encoderType: 'console'
  encodeLevel: 'CapitalLevelEncoder'
  encodeCaller: 'FullCallerEncoder'
